### ISSUE TITLE
can not read property logging of undefined

### ISSUE THREAD

**Issue by tomhuynen** [kristianmandrup/vue2-dragula-demo#1]
Hi,

In stalled like this:

yarn add kristianmandrup/vue-dragula#dev 

Afterwards:

var Vue = require('vue');
var VueDragula = require('vue2-dragula').default;

Vue.use(VueDragula);

Gives me the following error:

vue-dragula.js?c9f2:1345 Uncaught TypeError: Cannot read property 'logging' of undefined
    at new DragulaService (eval at <anonymous> (http://localhost:8080/app.js:1316:2), <anonymous>:1345:28)
    at createService (eval at <anonymous> (http://localhost:8080/app.js:1316:2), <anonymous>:1543:13)
    at VueDragula (eval at <anonymous> (http://localhost:8080/app.js:1316:2), <anonymous>:1587:18)
    at plugin (eval at <anonymous> (http://localhost:8080/app.js:1316:2), <anonymous>:1964:4)
    at Function.Vue.use (eval at <anonymous> (http://localhost:8080/app.js:610:2), <anonymous>:3188:14)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:947:2), <anonymous>:16:5)
    at Object.<anonymous> (http://localhost:8080/app.js:947:2)
    at __webpack_require__ (http://localhost:8080/app.js:554:30)
    at fn (http://localhost:8080/app.js:85:20)
    at Object.<anonymous> (http://localhost:8080/app.js:585:19)

Leaving out .default in the require would result in:

vue.js?3de6:3188 Uncaught TypeError: plugin.apply is not a function(…)Vue.use @ vue.js?3de6:3188(anonymous function) @ main.js?3479:8(anonymous function) @ app.js:947__webpack_require__ @ app.js:554fn @ app.js:85(anonymous function) @ app.js:585__webpack_require__ @ app.js:554(anonymous function) @ app.js:577(anonymous function) @ app.js:580

Best regards,
Tom

**Comment by kristianmandrup** [comment]
Hi Tom,

Glad you are trying it out!
Unfortunately I haven't had the opportunity yet to test all the latest refactoring of the new architecture in all the various usage combinations. Looks like it breaks when you don't pass  an options object when creating the service. I just pushed a fix to `kristianmandrup/vue-dragula#dev` branch, so please try this fix. I recommend you fork my branch and debug/work from there.
Best to use `npm link` to be able to debug and work with it locally ;)
Cheers!

**Comment by kristianmandrup** [comment]
Oh, forgot build. Pushed with a new dist build now ;) Should fix the logging.

**Comment by kristianmandrup** [comment]
Fixed the errors this evening. Now the demo works. It was a bit heavy on the logs when `logging: true`, so I added fine grained logging. Enjoy!

**Comment by tomhuynen** [comment]
Great, I'll give it another go this evening!
